name: Struo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge,bioconda,defaults
        channel-priority: true	
    - name: conda info
      shell: bash -l {0}
      run: conda info
    - name: conda install
      shell: bash -l {0}
      run: |
        mamba install python=${{ matrix.python-version }} snakemake ncbi-genome-download newick_utils r-base r-argparse r-curl r-data.table r-dplyr
    - name: Test util scripts
      shell: bash -l {0}
      working-directory: ./util_scripts/
      run: |
        ./GTDB_metadata_filter.R https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/ar122_metadata_r89.tsv | head -n 100
        ./genome_download.R --procs 2 tests/metadata_n3.tsv
        ./tree_prune.py tests/accession.txt https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/ar122_r89.tree
    - name: Test snakemake
      shell: bash -l {0}
      run: snakemake --jobs 2 --use-conda --configfile tests/config_default.yaml -Fqn
